Search.appendIndex(
    [
                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\EmptyResponseHandler",
            "name": "EmptyResponseHandler",
            "summary": "An\u0020empty\u0020response\u0020handler",
            "url": "classes/chillerlan-HTTP-Psr15-EmptyResponseHandler.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\EmptyResponseHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "EmptyResponseHandler\u0020constructor.",
            "url": "classes/chillerlan-HTTP-Psr15-EmptyResponseHandler.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\EmptyResponseHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-EmptyResponseHandler.html#method_handle"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\EmptyResponseHandler\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-EmptyResponseHandler.html#property_responseFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\EmptyResponseHandler\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-EmptyResponseHandler.html#property_status"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\MiddlewareException",
            "name": "MiddlewareException",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-MiddlewareException.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddleware",
            "name": "PriorityMiddleware",
            "summary": "A\u0020middleware\u0020with\u0020a\u0020priority\u0020setting",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddleware.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddleware\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "PriorityMiddleware\u0020constructor.",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddleware.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddleware\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddleware.html#method_process"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddleware\u003A\u003AgetPriority\u0028\u0029",
            "name": "getPriority",
            "summary": "Gets\u0020the\u0020priority\u0020value",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddleware.html#method_getPriority"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddleware\u003A\u003A\u0024middleware",
            "name": "middleware",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddleware.html#property_middleware"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddleware\u003A\u003A\u0024priority",
            "name": "priority",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddleware.html#property_priority"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddlewareInterface",
            "name": "PriorityMiddlewareInterface",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddlewareInterface.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityMiddlewareInterface\u003A\u003AgetPriority\u0028\u0029",
            "name": "getPriority",
            "summary": "Gets\u0020the\u0020priority\u0020value",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityMiddlewareInterface.html#method_getPriority"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityQueueDispatcher",
            "name": "PriorityQueueDispatcher",
            "summary": "A\u0020queue\u0020dispatcher\u0020that\u0020follows\u0020a\u0020priority\u0020order",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityQueueDispatcher.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityQueueDispatcher\u003A\u003AaddStack\u0028\u0029",
            "name": "addStack",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityQueueDispatcher.html#method_addStack"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityQueueDispatcher\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityQueueDispatcher.html#method_add"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\PriorityQueueDispatcher\u003A\u003AsortMiddleware\u0028\u0029",
            "name": "sortMiddleware",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-PriorityQueueDispatcher.html#method_sortMiddleware"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher",
            "name": "QueueDispatcher",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "QueueDispatcher\u0020constructor.",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003AaddStack\u0028\u0029",
            "name": "addStack",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#method_addStack"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#method_add"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#method_handle"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#method_process"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003AgetRunner\u0028\u0029",
            "name": "getRunner",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#method_getRunner"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003A\u0024middlewareStack",
            "name": "middlewareStack",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#property_middlewareStack"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\QueueDispatcher\u003A\u003A\u0024kernel",
            "name": "kernel",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-QueueDispatcher.html#property_kernel"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\RecursiveDispatcher",
            "name": "RecursiveDispatcher",
            "summary": "A\u0020simple\u0020middleware\u0020dispatcher\u0020based\u0020on\u0020Slim",
            "url": "classes/chillerlan-HTTP-Psr15-RecursiveDispatcher.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\RecursiveDispatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RecursiveDispatcher\u0020constructor.",
            "url": "classes/chillerlan-HTTP-Psr15-RecursiveDispatcher.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\RecursiveDispatcher\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Add\u0020a\u0020new\u0020middleware\u0020to\u0020the\u0020stack",
            "url": "classes/chillerlan-HTTP-Psr15-RecursiveDispatcher.html#method_add"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\RecursiveDispatcher\u003A\u003AaddStack\u0028\u0029",
            "name": "addStack",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-RecursiveDispatcher.html#method_addStack"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\RecursiveDispatcher\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-RecursiveDispatcher.html#method_handle"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15\\RecursiveDispatcher\u003A\u003A\u0024kernel",
            "name": "kernel",
            "summary": "",
            "url": "classes/chillerlan-HTTP-Psr15-RecursiveDispatcher.html#property_kernel"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait",
            "name": "FactoryTrait",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003AinitFactories\u0028\u0029",
            "name": "initFactories",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#method_initFactories"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024FACTORIES",
            "name": "FACTORIES",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_FACTORIES"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_responseFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024serverRequestFactory",
            "name": "serverRequestFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_serverRequestFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_streamFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024uploadedFileFactory",
            "name": "uploadedFileFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_uploadedFileFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024uriFactory",
            "name": "uriFactory",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_uriFactory"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024server",
            "name": "server",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_server"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\FactoryTrait\u003A\u003A\u0024emptyResponseHandler",
            "name": "emptyResponseHandler",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-FactoryTrait.html#property_emptyResponseHandler"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\PriorityQueueRequestHandlerTest",
            "name": "PriorityQueueRequestHandlerTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-PriorityQueueRequestHandlerTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\PriorityQueueRequestHandlerTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-PriorityQueueRequestHandlerTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\PriorityQueueRequestHandlerTest\u003A\u003AtestHandler\u0028\u0029",
            "name": "testHandler",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-PriorityQueueRequestHandlerTest.html#method_testHandler"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\PriorityQueueRequestHandlerTest\u003A\u003AtestNestedHandler\u0028\u0029",
            "name": "testNestedHandler",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-PriorityQueueRequestHandlerTest.html#method_testNestedHandler"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\PriorityQueueRequestHandlerTest\u003A\u003AgetNonPriorityMiddleware\u0028\u0029",
            "name": "getNonPriorityMiddleware",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-PriorityQueueRequestHandlerTest.html#method_getNonPriorityMiddleware"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\PriorityQueueRequestHandlerTest\u003A\u003AgetPriorityMiddleware\u0028\u0029",
            "name": "getPriorityMiddleware",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-PriorityQueueRequestHandlerTest.html#method_getPriorityMiddleware"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\PriorityQueueRequestHandlerTest\u003A\u003AtestInvalidMiddlewareException\u0028\u0029",
            "name": "testInvalidMiddlewareException",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-PriorityQueueRequestHandlerTest.html#method_testInvalidMiddlewareException"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest",
            "name": "QueueRequestHandlerTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest\u003A\u003AgetDispatcher\u0028\u0029",
            "name": "getDispatcher",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html#method_getDispatcher"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest\u003A\u003AtestDispatcher\u0028\u0029",
            "name": "testDispatcher",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html#method_testDispatcher"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest\u003A\u003AgetTestMiddlewareStack\u0028\u0029",
            "name": "getTestMiddlewareStack",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html#method_getTestMiddlewareStack"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest\u003A\u003AgetTestMiddleware\u0028\u0029",
            "name": "getTestMiddleware",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html#method_getTestMiddleware"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest\u003A\u003AgetTestFallbackHandler\u0028\u0029",
            "name": "getTestFallbackHandler",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html#method_getTestFallbackHandler"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\QueueRequestHandlerTest\u003A\u003AtestInvalidMiddlewareException\u0028\u0029",
            "name": "testInvalidMiddlewareException",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-QueueRequestHandlerTest.html#method_testInvalidMiddlewareException"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\RecursiveDispatcherTest",
            "name": "RecursiveDispatcherTest",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-RecursiveDispatcherTest.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\RecursiveDispatcherTest\u003A\u003AgetDispatcher\u0028\u0029",
            "name": "getDispatcher",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-RecursiveDispatcherTest.html#method_getDispatcher"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15\\RecursiveDispatcherTest\u003A\u003AtestInvalidMiddlewareException\u0028\u0029",
            "name": "testInvalidMiddlewareException",
            "summary": "",
            "url": "classes/chillerlan-HTTPTest-Psr15-RecursiveDispatcherTest.html#method_testInvalidMiddlewareException"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP\\Psr15",
            "name": "Psr15",
            "summary": "",
            "url": "namespaces/chillerlan-http-psr15.html"
        },                {
            "fqsen": "\\chillerlan\\HTTP",
            "name": "HTTP",
            "summary": "",
            "url": "namespaces/chillerlan-http.html"
        },                {
            "fqsen": "\\chillerlan",
            "name": "chillerlan",
            "summary": "",
            "url": "namespaces/chillerlan.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest\\Psr15",
            "name": "Psr15",
            "summary": "",
            "url": "namespaces/chillerlan-httptest-psr15.html"
        },                {
            "fqsen": "\\chillerlan\\HTTPTest",
            "name": "HTTPTest",
            "summary": "",
            "url": "namespaces/chillerlan-httptest.html"
        }            ]
);
